### PR TITLE
This pull request migrates Nodejs-ex application from MongoDB to Postgresql

### PR DESCRIPTION
**Pull request by phracek**
First commit copies sources from https://github.com/nodeshift-starters/nodejs-rest-http-crud

### CODE REVIEW

**Comment by phracek** [comment]
@lholmquist I have tested this pull request against nodejs-20, but I received a message like:

```bash
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'nodeshift@8.7.0',
npm WARN EBADENGINE   required: { node: '^16 || ^14 || ^12' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '10.1.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'openshift-rest-client@7.0.0',
npm WARN EBADENGINE   required: { node: '^16 || ^14 || ^12' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '10.1.0' }
npm WARN EBADENGINE }
```

What shall I change?

**Comment by lholmquist** [comment]
This line here should be updated: https://github.com/nodeshift-starters/nodejs-rest-http-crud/blob/main/package.json#L40

nodeshift version 11.0.0 is the latest that should get rid of those warnings

**Comment by phracek** [comment]
@lholmquist Hi Lucas, as you can see, I have added to dependencies also selling, but I still receive error:

```
[2/3] STEP 2/2: RUN /bin/sh -ic 'npm test'
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell

> nodejs-rest-http-crud@4.0.0 pretest
> eslint --ignore-path .gitignore .

sh: eslint: command not found
error: build error: building at STEP "RUN /bin/sh -ic 'npm test'": while running runtime: exit status 127
```

I have replaced calling in package.json like is mentioned here: https://bobbyhadz.com/blog/eslint-is-not-recognized-as-internal-or-external-command

```
  "scripts": {
    "pretest": "eslint --ignore-path .gitignore .",
    "test": "nyc --reporter=lcov mocha",
```

with 
```
  "scripts": {
    "pretest": "npx eslint --ignore-path .gitignore .",
    "test": "nyc --reporter=lcov mocha",
```

but it failed with 
```
[2/3] STEP 2/2: RUN /bin/sh -ic 'npm test'
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell

> nodejs-rest-http-crud@4.0.0 pretest
> npx eslint --ignore-path .gitignore .

npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path /opt/app-root/src/.npm-global
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/opt/app-root/src/.npm-global'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: /opt/app-root/src/.npm/_logs/2024-01-23T09_27_49_228Z-debug-0.log
npm notice
npm notice New minor version of npm available! 10.1.0 -> 10.3.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.3.0>
npm notice Run `npm install -g npm@10.3.0` to update!
npm notice```

**Comment by lholmquist** [comment]
@phracek i'll put it on the list to take a look

**Comment by phracek** [comment]
@lholmquist Did you have time to analyze it?

**Comment by lholmquist** [comment]
I think if it is just failing because of getting a linter setup/linting the code, maybe that part can just be skipped over for now.

It doesn't really affect the actual function of what the code should do.  i would also hate for a user to get tied up because of tooling.

I would just remove the `pretest` script from the package.json

**Comment by phracek** [comment]
Now it failed with reason:

```
[2/3] STEP 2/2: RUN /bin/sh -ic 'npm test'
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell

> nodejs-rest-http-crud@4.0.0 test
> nyc --reporter=lcov mocha

sh: nyc: command not found
error: build error: building at STEP "RUN /bin/sh -ic 'npm test'": while running runtime: exit status 127
```

I am trying now to remove the test by this commit https://github.com/sclorg/nodejs-ex/pull/277/commits/a512cf9edce453ccc19a3a3cbf2a99e4ca622beb and see what's happened.

**Comment by phracek** [comment]
@lholmquist Build was done properly, when `npm test` was removed, but runtime failed for this reason:

```
oc logs pod/nodejs-testing-1-95fzp
Environment:
	DEV_MODE=false
	NODE_ENV=production
	DEBUG_PORT=5858
Launching via npm...
npm info using npm@10.1.0
npm info using node@v20.9.0

> nodejs-rest-http-crud@4.0.0 start
> node .

node:internal/modules/cjs/loader:423
      throw err;
      ^

Error: Cannot find module '/opt/app-root/src/bin/www'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:415:19)
    at Module._findPath (node:internal/modules/cjs/loader:665:18)
    at resolveMainPath (node:internal/modules/run_main:15:25)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:24)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  path: '/opt/app-root/src/package.json',
  requestPath: '/opt/app-root/src'
}

Node.js v20.9.0
```

**Comment by lholmquist** [comment]
I don't see a `bin` folder in the list of committed files.    It's in the original repo https://github.com/nodeshift-starters/nodejs-rest-http-crud/tree/main/bin

**Comment by phracek** [comment]
The upstream pull request https://github.com/sclorg/s2i-nodejs-container/pull/419 passed. Tests are working properly. We can merge this issue.

**Pull request merged**
